// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type HRTHistory struct {
	DosageAt time.Time
	HRTType  string
}

type Notified struct {
	DosageAt   time.Time
	NotifiedAt sql.NullTime
}
